### ISSUE TITLE
看起来是xpath修改了

### ISSUE THREAD

**Issue by W4J1e** [princelai/auto_enaea#3]
登陆上了之后，提示“课程详情页加载失败”。但是不得不说python真是万能啊，辛苦开发者了。

**Comment by W4J1e** [comment]
总算摸索出来了，第159行修改为
`        self.driver.find_element_by_xpath(f'//*[@id="sideNav"]/ul/li[3]/a').click()`

**Comment by ouyangmland** [comment]
好像又不行了

**Comment by W4J1e** [comment]
@ouyangmland 我刚才看了一下，xpath没有改，我这也能正常登陆。不知道是不是不同地区或者不同学习导致的页面内容不同。
